workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    environment:
      groups:
        - keystore
        - google_credentials
      vars:
        PACKAGE_NAME: "ks.s.kss"
      flutter: 2.8.1
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '*'
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Set up key properties
        script: |
          echo $(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          echo $FCI_KEY_ALIAS
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Build AAB with Flutter  
        script: |
          cd . && flutter build apk --release --build-name=1.0.0 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          #cd . && flutter build appbundle --release --build-name=1.0.$PROJECT_BUILD_NUMBER --build-number=$PROJECT_BUILD_NUMBER
      - name: Build finished successfully
        script: touch ~/SUCCESS
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients: 
          - kalgi@nevercode.io
      scripts:
      - name: Report build status
        script: |
          if [ -f ~/SUCCESS ] ; then
            echo "build successful"
          else
            echo "build failed"
          fi    
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        in_app_update_priority: 0
